// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-Mwbh4D0xRiwxYFQQOyEnCt3fQgVjRM',
    appId: '1:481141840521:web:2cab5c77a1aaa7e238c458',
    messagingSenderId: '481141840521',
    projectId: 'directdeal-76a7c',
    authDomain: 'directdeal-76a7c.firebaseapp.com',
    storageBucket: 'directdeal-76a7c.firebasestorage.app',
    measurementId: 'G-1R4E3WLR9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwG9N0q1G49NW4TsSwzsais5uA4h414mw',
    appId: '1:481141840521:android:45cda6293a08dd7f38c458',
    messagingSenderId: '481141840521',
    projectId: 'directdeal-76a7c',
    storageBucket: 'directdeal-76a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVReUzEjrZsnffuul-dIQOUE1f5_k45lU',
    appId: '1:481141840521:ios:5c995313cd119d2d38c458',
    messagingSenderId: '481141840521',
    projectId: 'directdeal-76a7c',
    storageBucket: 'directdeal-76a7c.firebasestorage.app',
    iosBundleId: 'com.example.clothingShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVReUzEjrZsnffuul-dIQOUE1f5_k45lU',
    appId: '1:481141840521:ios:5c995313cd119d2d38c458',
    messagingSenderId: '481141840521',
    projectId: 'directdeal-76a7c',
    storageBucket: 'directdeal-76a7c.firebasestorage.app',
    iosBundleId: 'com.example.clothingShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt-Mwbh4D0xRiwxYFQQOyEnCt3fQgVjRM',
    appId: '1:481141840521:web:dee60efdcb79c80f38c458',
    messagingSenderId: '481141840521',
    projectId: 'directdeal-76a7c',
    authDomain: 'directdeal-76a7c.firebaseapp.com',
    storageBucket: 'directdeal-76a7c.firebasestorage.app',
    measurementId: 'G-QD0VLMPQRZ',
  );
}
